name: Build and Pack

on: [push, pull_request]

jobs:
#########################################################################################
## Prepare and create release
#########################################################################################
  release: 
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') 

    # Sets permissions of the GITHUB_TOKEN to allow updating the branches
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: bla
      run: |
       echo "bla"

#########################################################################################
## Update Contributors List in README.md
#########################################################################################
  contrib-readme-job:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
        - name: Contribute List
          uses: akhilmhdh/contributors-readme-action@v2.3.10
          with:
              image_size: 50  
              use_username: true
              columns_per_row: 8
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  contrib-readme-job2:
    if: github.event_name == 'release' && github.event.action == 'published' # Only run on release but not on prerelease
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
        - name: Contribute List
          uses: akhilmhdh/contributors-readme-action@v2.3.10
          with:
              image_size: 50  
              use_username: true
              columns_per_row: 8
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#########################################################################################
## Update the Web Installer on a release
#########################################################################################
# Make sure to also update update-webinstaller.yml!
  update-web-installer:
    if: github.event_name == 'release' && github.event.action == 'published' # Only run on release but not on prerelease
    needs: [release]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get version of last release
      id: last_release
      uses: mindojo/get-latest-release@0b8ef1434d7468d6bffcc8263baff5c777f72321
      with:
        myToken: ${{ github.token }}
        exclude_types: "draft|prerelease"
        view_top: 1     

    - name: Add binary to Web Installer and update manifest
      run: |
        echo "Updating Web installer to use firmware from ${{ steps.last_release.outputs.tag_name }}..."
        rm -f docs/binary/firmware.bin
        wget ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.last_release.outputs.tag_name }}/AI-on-the-edge-device__update__${{ steps.last_release.outputs.tag_name }}.zip
        unzip AI-on-the-edge-device__update__${{ steps.last_release.outputs.tag_name }}.zip
        cp -f firmware.bin docs/binary/firmware.bin
        echo "Updating index and manifest file..."
        sed -i 's/$VERSION/${{ steps.last_release.outputs.tag_name }}/g' docs/index.html
        sed -i 's/$VERSION/${{ steps.last_release.outputs.tag_name }}/g' docs/manifest.json

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'docs'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3  # Note: v4 does not work!
