name: Build and Pack

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Building..."

  update-pages:
    if: github.event_name == 'release' && github.event.action == 'published' # Only run on release but not on prerelease
    runs-on: ubuntu-latest

    steps:
    - run: echo "We are on a release"
