# Reply Bot

name: Reply-Bot

on:
  discussion:
    types: [created]
  discussion_comment: # testing
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  bot-response:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  

    - name: analyze
      id: analyze
      run: |
        #echo "$GITHUB_CONTEXT"
        python discussion-bot/main.py --actor "${{ github.actor }}" --title "${{ github.event.discussion.title }}" --body "${{ github.event.discussion.body }}"
        echo "response=$(cat response.md)" >> $GITHUB_OUTPUT
        cat response.md
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Run discussion-auto-responder
      uses: wesleyscholl/discussion-auto-responder@v1.0.8
      id: autoresponder-comment
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        comment_body: "${{ steps.analyze.outputs.response }}"
        delay_milliseconds: 1000

