# Reply Bot

name: Reply-Bot

on:
  discussion:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  bot-response:
    runs-on: ubuntu-latest
    steps:
       - name: analyze
         run: |
          response="Hello World"

      - name: Run discussion-auto-responder
        uses: wesleyscholl/discussion-auto-responder@v1.0.8
        id: autoresponder-comment
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          comment_body: "${response}"
          delay_milliseconds: 1000
       
