# Reply Bot

name: Reply-Bot

on:
  discussion:
    types: [created]
  discussion_comment: # testing
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  bot-response:
    runs-on: ubuntu-24.04
    steps:
    - name: analyze
      id: analyze
      run: |
        echo "response=Hello_World" >> $GITHUB_OUTPUT
        echo $GLOBAL_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo $GITHUB_OUTPUT
        echo "Issue actor: ${{ github.actor }}"
        echo "Issue title: ${{ github.event.discussion.title }}"
        echo "Issue body: ${{ github.event.discussion.body }}"
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}


    - name: Run discussion-auto-responder
      uses: wesleyscholl/discussion-auto-responder@v1.0.8
      id: autoresponder-comment
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        comment_body: "${{ steps.analyze.outputs.response }}"
        delay_milliseconds: 1000

